name: 'Stage 5 Envoy'
on: [push]


jobs:
  container:
    name: 'Container Build'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      registryName: "2021hackathon"
      registryLoginServer: "2021hackathon.azurecr.io"

    defaults:
      run:
        shell: bash
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment
        run: |
          az aks get-credentials --resource-group ${{ secrets.UNIQUE_NAME }} --name ${{ secrets.UNIQUE_NAME }}

      - name: Docker Login to Registry
        run: |
          az acr login --name ${{ env.registryName }}
          
      # Build Old NGINX Frontend
      - name: Build NGINX Base Frontend
        run: docker build -t ${{ env.registryLoginServer }}/envoy:latest ./stage_5_envoy/envoy/

      - name: Push NGINX Base Frontend
        run: docker push ${{ env.registryLoginServer }}/envoy:latest

      - name: Deploy Manifests
        run: |
          kubectl apply -f ./stage_5_envoy/